
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Trogtor
 */
public class PracticeFrame extends javax.swing.JFrame {
    int numTotes;
    int teamNum;
    int matchNum;
    int autoPoints;
    int teleOpPoints;
    int foulPoints;
    int gamePoints;
    String name;
    int s1Totes;
    int s2Totes;
    int s3Totes;
    int s4Totes;
    int s5Totes;
    boolean s1Can;
    boolean s2Can;
    boolean s3Can;
    boolean s4Can;
    boolean s5Can;
    boolean s1Noodle;
    boolean s2Noodle;
    boolean s3Noodle;
    boolean s4Noodle;
    boolean s5Noodle;
    String notes;
    String number;
    boolean coopSet;
    boolean coopStack;
    int coopStackPoints;
    int coopSetPoints;
    int totalPoints;
    int totalAllPoints;
         int sP;
         int tC;
         int tC2;
         int tC3;
         int tC4;
         int tC5;
         int sP1;
         int sP2;
         int sP3;
         int sP4;
         int sP5;
         int s1N;
         int s2N;
         int s3N;
         int s4N;
         int s5N;

    /**
     * Creates new form PracticeFrame
     */
    public PracticeFrame() {
        initComponents();
        numTotes = 0;
        teamNum = -1;
        autoPoints = 0;
        teleOpPoints = 0;
        foulPoints = 0;
        gamePoints = 0;
        name = "";
        s1Totes = 0;
        s2Totes = 0;
        s3Totes = 0;
        s4Totes = 0;
        s5Totes = 0;
        s1Can = true;
        s2Can = true;
        s3Can = true;
        s4Can = true;
        s5Can = true;
        s1Noodle = true;
        s2Noodle = true;
        s3Noodle = true; 
        s4Noodle = true;
        s5Noodle = true;
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InternalFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        StandScout = new javax.swing.JLabel();
        Totes = new javax.swing.JLabel();
        Autonomous = new javax.swing.JLabel();
        TrashCan = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jSpinner10 = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InternalFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.black));
        InternalFrame.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Autonomous Points:\n\nDrive to Zone = 4 Points\nTote in Zone (3 Possible) = 6 points\nContainer in Zone (3 Possible) = 8 points\nStacked Tote Set of 3 in Zone = 20 points\n\nTele-Op Points:\n\nGray Tote = 2 Points\nCan = 4x Per Tote in Stack\nLitter in Recycle Bin = 6 Points\n\nHuman Player Points (Not Necessary):\n\nLitter in Landfill = 1 Point\nLitter in Opponent Zone = 4 Points\n"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        StandScout.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        StandScout.setText("Torbots Stand Scouting");
        StandScout.setAlignmentX(0.5F);

        Totes.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        Totes.setText("Autonomous Points");
        Totes.setToolTipText("");

        Autonomous.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        Autonomous.setText("Foul Points");

        TrashCan.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        TrashCan.setText("Tele-Op Points");

        jSpinner1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner1FocusLost(evt);
            }
        });

        jSpinner2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner2FocusLost(evt);
            }
        });

        jSpinner3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner3FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel3.setText("Stack #1");

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel4.setText("Stack #2");

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel5.setText("Stack #3");

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel6.setText("Stack #4");

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel7.setText("Stack #5");

        jLabel8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel8.setText("# of Totes");

        jLabel9.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel9.setText("# of Totes");

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel10.setText("# of Totes");

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel11.setText("# of Totes");

        jLabel12.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel12.setText("# of Totes");

        jSpinner5.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinner5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner5FocusLost(evt);
            }
        });

        jSpinner6.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinner6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner6FocusLost(evt);
            }
        });

        jSpinner7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinner7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner7FocusLost(evt);
            }
        });

        jSpinner8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinner8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner8FocusLost(evt);
            }
        });

        jSpinner9.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner9.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinner9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner9FocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel13.setText("Can?");

        jLabel14.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel14.setText("Can?");

        jLabel15.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel15.setText("Can?");

        jLabel16.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel16.setText("Can?");

        jLabel17.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel17.setText("Can?");

        jTextField1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel2.setText("Team #");

        jLabel18.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel18.setText("Team Name");

        jTextField2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel19.setText("Match #");

        jTextField3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel22.setText("Noodle?");

        jLabel23.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel23.setText("Noodle?");

        jLabel24.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel24.setText("Noodle?");

        jLabel25.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel25.setText("Noodle?");

        jLabel26.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabel26.setText("Noodle?");

        jComboBox2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox2FocusLost(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox3FocusLost(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox4FocusLost(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox5FocusLost(evt);
            }
        });

        jComboBox6.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox6FocusLost(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox7.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox7FocusLost(evt);
            }
        });

        jComboBox8.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox8FocusLost(evt);
            }
        });

        jComboBox9.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox9FocusLost(evt);
            }
        });

        jComboBox10.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox10FocusLost(evt);
            }
        });

        jComboBox11.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox11FocusLost(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("");
        jScrollPane2.setViewportView(jTextArea2);

        jCheckBox1.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        jCheckBox1.setText("Coopertition? (20 PTS) 2 Totes");

        jCheckBox2.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        jCheckBox2.setText("Coopertition Stack? (40PTS) 4 Totes");

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel21.setText("Notes:");

        jSpinner10.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jSpinner10.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel27.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        jLabel27.setText("Total Alliance Points");

        jComboBox12.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chute", "Landfill", "Both" }));
        jComboBox12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox12FocusLost(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        jLabel28.setText("Loading Type");

        jComboBox13.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        jComboBox13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox13FocusLost(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tekton Pro", 0, 16)); // NOI18N
        jLabel29.setText("Maximum # of Totes in Stack");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel1.setText("Stack Point Calculator");

        jButton1.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel20.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel20.setText("Pit Scouting Info:");

        jLabel30.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel30.setText("Scoring Info:");

        javax.swing.GroupLayout InternalFrameLayout = new javax.swing.GroupLayout(InternalFrame);
        InternalFrame.setLayout(InternalFrameLayout);
        InternalFrameLayout.setHorizontalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternalFrameLayout.createSequentialGroup()
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3)
                            .addComponent(jLabel22)
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.LEADING, 0, 58, Short.MAX_VALUE)
                                            .addComponent(jSpinner5))
                                        .addGap(28, 28, 28)))
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel23)
                                    .addComponent(jSpinner6)
                                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel15)
                                                            .addComponent(jLabel24)
                                                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(89, 89, 89))
                                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(jSpinner7))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(jSpinner8)))
                                                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                                                .addGap(78, 78, 78)
                                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel25)
                                                                    .addComponent(jLabel16)
                                                                    .addComponent(jComboBox10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                            .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jSpinner9)
                                                    .addComponent(jComboBox11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                                        .addGap(139, 139, 139)
                                                        .addComponent(StandScout))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jCheckBox1)
                                                            .addComponent(jCheckBox2))
                                                        .addGap(61, 61, 61))))
                                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel6)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel21)
                                                            .addComponent(jLabel20))))
                                                .addGap(18, 18, 18))))
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel30)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(InternalFrameLayout.createSequentialGroup()
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternalFrameLayout.createSequentialGroup()
                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternalFrameLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(Totes))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternalFrameLayout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)))
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TrashCan)))))
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Autonomous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner3))
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel27))
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addGroup(InternalFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 58, Short.MAX_VALUE)))
                                .addGap(593, 593, 593))))))
        );
        InternalFrameLayout.setVerticalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InternalFrameLayout.createSequentialGroup()
                        .addComponent(StandScout)
                        .addGap(8, 8, 8)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Totes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Autonomous)
                            .addComponent(TrashCan)
                            .addComponent(jLabel27))
                        .addGap(9, 9, 9)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel20)
                        .addGap(1, 1, 1)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner6)
                                .addComponent(jSpinner5)
                                .addComponent(jSpinner7))
                            .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner8)
                                .addComponent(jSpinner9)))
                        .addGap(1, 1, 1)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2))
                        .addGap(13, 13, 13)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(7, 7, 7)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel1)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(68, 68, 68))
                    .addGroup(InternalFrameLayout.createSequentialGroup()
                        .addGroup(InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InternalFrameLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        // TODO add your handling code here:
        points();
    }//GEN-LAST:event_jButton1FocusGained

    private void jComboBox13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox13FocusLost
        // TODO add your handling code here:
        jComboBox13.getSelectedItem();
    }//GEN-LAST:event_jComboBox13FocusLost

    private void jComboBox12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox12FocusLost
        // TODO add your handling code here:
        jComboBox12.getSelectedItem();
    }//GEN-LAST:event_jComboBox12FocusLost

    private void jComboBox11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox11FocusLost
        // TODO add your handling code here:
        s5Can = (((String)jComboBox11.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox11FocusLost

    private void jComboBox10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox10FocusLost
        // TODO add your handling code here:
        s4Can = (((String)jComboBox10.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox10FocusLost

    private void jComboBox9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox9FocusLost
        // TODO add your handling code here:
        s3Can = (((String)jComboBox9.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox9FocusLost

    private void jComboBox8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox8FocusLost
        // TODO add your handling code here:
        s2Can = (((String)jComboBox8.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox8FocusLost

    private void jComboBox7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox7FocusLost
        // TODO add your handling code here:
        s1Can = (((String)jComboBox7.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox7FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        points();
        setAllValues();
        makeCSV();
        clearForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox6FocusLost
        // TODO add your handling code here:
        s5Noodle = (((String)jComboBox6.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox6FocusLost

    private void jComboBox5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox5FocusLost
        // TODO add your handling code here:
        s4Noodle = (((String)jComboBox5.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox5FocusLost

    private void jComboBox4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox4FocusLost
        // TODO add your handling code here:
        s3Noodle = (((String)jComboBox4.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox4FocusLost

    private void jComboBox3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox3FocusLost
        // TODO add your handling code here:
        s2Noodle = (((String)jComboBox3.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox3FocusLost

    private void jComboBox2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusLost
        // TODO add your handling code here:
        s1Noodle = (((String)jComboBox2.getSelectedItem()).equals("Yes"));
    }//GEN-LAST:event_jComboBox2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        try{
            matchNum = Integer.parseInt(jTextField3.getText());
        }
        catch(NumberFormatException e){
            jTextField3.setText("Enter Valid Number");
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
       name = jTextField2.getText();
//        String filename = "Team Number " + teamNum + " " + number + ".txt";
//        BufferedReader br = null;
//        String text = "";
//        String str;
//        try {
//
//            br = new BufferedReader(new FileReader(filename));
//            while((str=br.readLine())!=null) {
//                text+="\n" + str;
//                jTextArea3.setText(text);
//            }
//        } catch (FileNotFoundException e) {
//            System.out.println("Fail");
//        } catch (IOException e) {
//        }
//        finally {
//            if (br != null) {
//                try {
//                    br.close();
//                } catch (IOException e) {
//                }
//            }
//        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:

        try{
            teamNum = Integer.parseInt(jTextField1.getText());
        }
        catch(NumberFormatException e){
            jTextField1.setText("Enter Valid Number");
        }
        coopSet = jCheckBox1.isSelected();
        if (jCheckBox1.isSelected()){
            coopSetPoints = 20;
        }
        else{
            coopSetPoints = 0;
        }
        coopStack = jCheckBox2.isSelected();
        if(jCheckBox2.isSelected()){
            coopStackPoints = 40;
        }
        else{
            coopStackPoints = 0;
        }
        number = jTextField1.getText();
        String filename = "Team Number " + teamNum + " " + name + ".txt";
        BufferedReader br = null;
        String text = "";
        String str;
        try {

            br = new BufferedReader(new FileReader(filename));
            while((str=br.readLine())!=null) {
                text+="\n" + str;
                jTextArea3.setText(text);
            }
        } catch (FileNotFoundException e) {
            System.out.println("Fail");
        } catch (IOException e) {
        }
        finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                }
            }
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jSpinner9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner9FocusLost
        // TODO add your handling code here:
        s5Totes = Integer.parseInt(jSpinner9.getValue().toString());
    }//GEN-LAST:event_jSpinner9FocusLost

    private void jSpinner8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner8FocusLost
        // TODO add your handling code here:
        s4Totes = Integer.parseInt(jSpinner8.getValue().toString());
    }//GEN-LAST:event_jSpinner8FocusLost

    private void jSpinner7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner7FocusLost
        // TODO add your handling code here:
        s3Totes = Integer.parseInt(jSpinner7.getValue().toString());
    }//GEN-LAST:event_jSpinner7FocusLost

    private void jSpinner6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner6FocusLost
        // TODO add your handling code here:
        s2Totes = Integer.parseInt(jSpinner6.getValue().toString());
    }//GEN-LAST:event_jSpinner6FocusLost

    private void jSpinner5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner5FocusLost
        // TODO add your handling code here:
        s1Totes = Integer.parseInt(jSpinner5.getValue().toString());
    }//GEN-LAST:event_jSpinner5FocusLost

    private void jSpinner3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner3FocusLost
        // TODO add your handling code here:
        foulPoints = Integer.parseInt(jSpinner3.getValue().toString());
    }//GEN-LAST:event_jSpinner3FocusLost

    private void jSpinner2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner2FocusLost
        // TODO add your handling code here:
        autoPoints = Integer.parseInt(jSpinner2.getValue().toString());
    }//GEN-LAST:event_jSpinner2FocusLost

    private void jSpinner1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner1FocusLost
        // TODO add your handling code here:
        teleOpPoints = Integer.parseInt(jSpinner1.getValue().toString());
    }//GEN-LAST:event_jSpinner1FocusLost

     
    /**
     * @param args the command line arguments
     */
    
     public void setAllValues(){
        teleOpPoints = Integer.parseInt(jSpinner1.getValue().toString());
        autoPoints = Integer.parseInt(jSpinner2.getValue().toString());
        foulPoints = Integer.parseInt(jSpinner3.getValue().toString()); 
        numTotes = s1Totes + s2Totes + s3Totes + s4Totes + s5Totes;
        gamePoints = teleOpPoints + autoPoints - foulPoints + coopSetPoints + coopStackPoints;
        notes = jTextArea2.getText();
    }
    public void points(){
        s1Totes = Integer.parseInt(jSpinner5.getValue().toString());
        s2Totes = Integer.parseInt(jSpinner6.getValue().toString());
        s3Totes = Integer.parseInt(jSpinner7.getValue().toString());
        s4Totes = Integer.parseInt(jSpinner8.getValue().toString());
        s5Totes = Integer.parseInt(jSpinner9.getValue().toString());
        s1Noodle = (((String)jComboBox2.getSelectedItem()).equals("Yes"));
        s2Noodle = (((String)jComboBox3.getSelectedItem()).equals("Yes"));
        s3Noodle = (((String)jComboBox4.getSelectedItem()).equals("Yes"));
        s4Noodle = (((String)jComboBox5.getSelectedItem()).equals("Yes"));
        s5Noodle = (((String)jComboBox6.getSelectedItem()).equals("Yes"));
        s1Can = (((String)jComboBox7.getSelectedItem()).equals("Yes"));
        s2Can = (((String)jComboBox8.getSelectedItem()).equals("Yes"));
        s3Can = (((String)jComboBox9.getSelectedItem()).equals("Yes"));
        s4Can = (((String)jComboBox10.getSelectedItem()).equals("Yes"));
        s5Can = (((String)jComboBox11.getSelectedItem()).equals("Yes"));
  
         if((((String)jComboBox7.getSelectedItem()).equals("Yes"))){
             tC = 4*s1Totes + 2*s1Totes;
             sP1 = tC;
         }
         else{
             tC = 0;
             sP1 = 2*s1Totes;
         }
         if((((String)jComboBox8.getSelectedItem()).equals("Yes"))){
         tC2 = 4*s2Totes + 2*s2Totes;
         sP2 = tC2;
     }
         else{
         sP2 = 2*s2Totes;    
         tC2 = 0;
     }
         if((((String)jComboBox9.getSelectedItem()).equals("Yes"))){
             tC3 = 4*s3Totes + 2*s3Totes;
             sP3 = tC3;
     }
         else{
         tC3 = 0;
          sP3 = 2*s3Totes;
     }
         if((((String)jComboBox10.getSelectedItem()).equals("Yes"))){
             tC4 = 4*s4Totes + 2*s4Totes;
              sP4 = tC4;
     }
         else{
         tC4 = 0;
          sP4 = 2*s4Totes;
     }
         if((((String)jComboBox11.getSelectedItem()).equals("Yes"))){
             tC5 = 4*s5Totes + 2*s5Totes;
              sP5 = tC5;
     }
         else{
         tC5 = 0;
          sP5 = 2*s5Totes;
     } 
         if((((String)jComboBox2.getSelectedItem()).equals("Yes")) && (((String)jComboBox7.getSelectedItem()).equals("Yes"))){
             s1N = 6;
         }
         else{
             s1N = 0;
         }
         if((((String)jComboBox3.getSelectedItem()).equals("Yes"))&& (((String)jComboBox8.getSelectedItem()).equals("Yes"))){
             s2N = 6;
         }
         else{
             s2N = 0;
         }
         if((((String)jComboBox4.getSelectedItem()).equals("Yes"))&& (((String)jComboBox9.getSelectedItem()).equals("Yes"))){
             s3N = 6;
         }
         else{
             s3N = 0;
         }
         if((((String)jComboBox5.getSelectedItem()).equals("Yes"))&& (((String)jComboBox10.getSelectedItem()).equals("Yes"))){
             s4N = 6;
         }
         else{
             s4N = 0;
         }
         if((((String)jComboBox6.getSelectedItem()).equals("Yes"))&& (((String)jComboBox11.getSelectedItem()).equals("Yes"))){
             s5N = 6;
         }
         else{
             s5N = 0;
         }
         sP = sP1 + sP2 + sP3 + sP4 + sP5 + s1N + s2N + s3N + s4N + s5N;
         jTextField4.setText(Integer.toUnsignedString(sP));
         jTextField4.update(jTextField4.getGraphics());
     }
    public void makeCSV(){
        String fileName = "Match" + matchNum + " " + teamNum + ".csv";
        try{
            FileWriter writer = new FileWriter(fileName,true);
            writer.append(matchNum + "," + teamNum + "," + autoPoints + "," + teleOpPoints + "," 
                   + foulPoints + "," + gamePoints + "," + sP + "," + totalAllPoints + "," + numTotes + "," 
                    + s1Totes + "," + s2Totes + "," + s3Totes + "," + s4Totes + "," + s5Totes + ","
                    + s1Can + "," + s2Can + "," + s3Can + "," + s4Can + "," + s5Can + "," + s1Noodle 
                    + "," + s2Noodle + "," + s3Noodle + "," + s4Noodle + "," + s5Noodle 
                    + "," + jComboBox12.getSelectedItem() + "," + jComboBox13.getSelectedItem() + "," + coopSet + "," + coopStack + "," + notes + ",");
            writer.flush();
            writer.close();
        }
        catch(IOException e){
        }
    }
     public void run() {
        validate();
     }
    public void clearForm(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextArea1.setText("Autonomous Points:\n" +
"\n" +
"Drive to Zone = 4 Points\n" +
"Tote in Zone (3 Possible) = 6 points\n" +
"Container in Zone (3 Possible) = 8 points\n" +
"Stacked Tote Set of 3 in Zone = 20 points\n" +
"\n" +
"Tele-Op Points:\n" +
"\n" +
"Gray Tote = 2 Points\n" +
"Can = 4x Per Tote in Stack\n" +
"Litter in Recycle Bin = 6 Points\n" +
"\n" +
"Human Player Points (Not Necessary):\n" +
"\n" +
"Litter in Landfill = 1 Point\n" +
"Litter in Opponent Zone = 4 Points");
        jTextArea2.setText(" ");
        jTextArea3.setText(" ");
        jButton2.setText("Save");
        jSpinner1.setValue(new Integer (0));
        jSpinner2.setValue(new Integer (0));
        jSpinner3.setValue(new Integer (0));
        jSpinner5.setValue(new Integer (0));
        jSpinner6.setValue(new Integer (0));
        jSpinner7.setValue(new Integer (0));
        jSpinner8.setValue(new Integer (0));
        jSpinner9.setValue(new Integer (0));
        jSpinner10.setValue(new Integer (0));
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        jComboBox10.setSelectedIndex(0);
        jComboBox11.setSelectedIndex(0);
        jComboBox12.setSelectedIndex(0);
        jComboBox13.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jTextField4.setText("");
        sP = 0;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autonomous;
    private javax.swing.JPanel InternalFrame;
    private javax.swing.JLabel StandScout;
    private javax.swing.JLabel Totes;
    private javax.swing.JLabel TrashCan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
